#!/bin/bash
# Quick Reference Commands for Refactoring Screencast

echo "=== Code Refactoring Screencast - Quick Commands ==="
echo ""
echo "1. SETUP (Before Recording):"
echo "   cd '/Volumes/[C] Windows 11/eventflow/eventflow-dashboard'"
echo "   git checkout -b refactoring-demo"
echo "   code ."
echo ""
echo "2. TEST COMMANDS (During Recording):"
echo "   node engagement.js"
echo "   clear"
echo ""
echo "3. CLEANUP (After Recording):"
echo "   git checkout main"
echo "   git branch -D refactoring-demo"
echo "   rm engagement.js engagement-step1.js engagement-step2.js"
echo ""
echo "4. FILES CREATED:"
echo "   - engagement.js (initial messy version)"
echo "   - engagement-step1.js (with extracted conditions)"
echo "   - engagement-step2.js (with constants)"
echo "   - refactoring-recording-guide.md (this guide)"
echo ""
echo "Remember: Type SLOWLY when introducing new concepts!"